// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bstoken.sql

package sqlc

import (
	"context"
)

const selectBootstrapToken = `-- name: SelectBootstrapToken :one
SELECT
    bootstrap_token_b64
FROM
    devices
WHERE
    id = ?
`

func (q *Queries) SelectBootstrapToken(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, selectBootstrapToken, id)
	var bootstrap_token_b64 []byte
	err := row.Scan(&bootstrap_token_b64)
	return bootstrap_token_b64, err
}

const updateBootstrapToken = `-- name: UpdateBootstrapToken :exec
UPDATE
    devices
SET
    bootstrap_token_b64 = ?,
    bootstrap_token_at = CURRENT_TIMESTAMP
WHERE
    id = ?
LIMIT
    1
`

type UpdateBootstrapTokenParams struct {
	BootstrapTokenB64 []byte
	ID                string
}

func (q *Queries) UpdateBootstrapToken(ctx context.Context, arg UpdateBootstrapTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateBootstrapToken, arg.BootstrapTokenB64, arg.ID)
	return err
}
