// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: certauth.sql

package sqlc

import (
	"context"
)

const selectCountCertAuthByHash = `-- name: SelectCountCertAuthByHash :one
SELECT
    COUNT(*)
FROM
    cert_auth_associations
WHERE
    sha256 = ?
`

func (q *Queries) SelectCountCertAuthByHash(ctx context.Context, sha256 string) (int64, error) {
	row := q.db.QueryRowContext(ctx, selectCountCertAuthByHash, sha256)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const selectCountCertAuthByID = `-- name: SelectCountCertAuthByID :one
SELECT
    COUNT(*)
FROM
    cert_auth_associations
WHERE
    id = ?
`

func (q *Queries) SelectCountCertAuthByID(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, selectCountCertAuthByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const selectCountCertAuthByIDAndHash = `-- name: SelectCountCertAuthByIDAndHash :one
SELECT
    COUNT(*)
FROM
    cert_auth_associations
WHERE
    id = ?
    AND sha256 = ?
`

type SelectCountCertAuthByIDAndHashParams struct {
	ID     string
	Sha256 string
}

func (q *Queries) SelectCountCertAuthByIDAndHash(ctx context.Context, arg SelectCountCertAuthByIDAndHashParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, selectCountCertAuthByIDAndHash, arg.ID, arg.Sha256)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const selectEnrollmentFromHash = `-- name: SelectEnrollmentFromHash :one
SELECT
    id
FROM
    cert_auth_associations
WHERE
    sha256 = ?
LIMIT
    1
`

func (q *Queries) SelectEnrollmentFromHash(ctx context.Context, sha256 string) (string, error) {
	row := q.db.QueryRowContext(ctx, selectEnrollmentFromHash, sha256)
	var id string
	err := row.Scan(&id)
	return id, err
}

const upsertCertHashAssociation = `-- name: UpsertCertHashAssociation :exec
INSERT INTO
    cert_auth_associations (id, sha256)
VALUES
    (?, ?) AS new ON DUPLICATE KEY
UPDATE
    sha256 = new.sha256
`

type UpsertCertHashAssociationParams struct {
	ID     string
	Sha256 string
}

func (q *Queries) UpsertCertHashAssociation(ctx context.Context, arg UpsertCertHashAssociationParams) error {
	_, err := q.db.ExecContext(ctx, upsertCertHashAssociation, arg.ID, arg.Sha256)
	return err
}
