// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mdm.sql

package sqlc

import (
	"context"
	"database/sql"
)

const selectTokenUpdateTally = `-- name: SelectTokenUpdateTally :one
SELECT
    token_update_tally
FROM
    enrollments
WHERE
    id = ?
`

func (q *Queries) SelectTokenUpdateTally(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRowContext(ctx, selectTokenUpdateTally, id)
	var token_update_tally int32
	err := row.Scan(&token_update_tally)
	return token_update_tally, err
}

const updateDeviceTokenUpdate = `-- name: UpdateDeviceTokenUpdate :exec
UPDATE
    devices
SET
    token_update = ?,
    token_update_at = CURRENT_TIMESTAMP
WHERE
    id = ?
LIMIT
    1
`

type UpdateDeviceTokenUpdateParams struct {
	TokenUpdate []byte
	ID          string
}

func (q *Queries) UpdateDeviceTokenUpdate(ctx context.Context, arg UpdateDeviceTokenUpdateParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceTokenUpdate, arg.TokenUpdate, arg.ID)
	return err
}

const updateDeviceTokenUpdateWithUnlock = `-- name: UpdateDeviceTokenUpdateWithUnlock :exec
UPDATE
    devices
SET
    token_update = ?,
    token_update_at = CURRENT_TIMESTAMP,
    unlock_token = ?,
    unlock_token_at = CURRENT_TIMESTAMP
WHERE
    id = ?
LIMIT
    1
`

type UpdateDeviceTokenUpdateWithUnlockParams struct {
	TokenUpdate []byte
	UnlockToken []byte
	ID          string
}

func (q *Queries) UpdateDeviceTokenUpdateWithUnlock(ctx context.Context, arg UpdateDeviceTokenUpdateWithUnlockParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceTokenUpdateWithUnlock, arg.TokenUpdate, arg.UnlockToken, arg.ID)
	return err
}

const updateDisableEnrollment = `-- name: UpdateDisableEnrollment :exec
UPDATE
    enrollments
SET
    enabled = 0,
    token_update_tally = 0,
    last_seen_at = CURRENT_TIMESTAMP
WHERE
    device_id = ?
    AND enabled = 1
`

func (q *Queries) UpdateDisableEnrollment(ctx context.Context, deviceID string) error {
	_, err := q.db.ExecContext(ctx, updateDisableEnrollment, deviceID)
	return err
}

const upsertAuthenticate = `-- name: UpsertAuthenticate :exec
INSERT INTO
    devices (
        id,
        identity_cert,
        serial_number,
        authenticate,
        authenticate_at
    )
VALUES
    (?, ?, ?, ?, CURRENT_TIMESTAMP) AS new ON DUPLICATE KEY
UPDATE
    identity_cert = new.identity_cert,
    serial_number = new.serial_number,
    bootstrap_token_b64 = NULL,
    bootstrap_token_at = NULL,
    authenticate = new.authenticate,
    authenticate_at = CURRENT_TIMESTAMP
`

type UpsertAuthenticateParams struct {
	ID           string
	IdentityCert []byte
	SerialNumber sql.NullString
	Authenticate []byte
}

func (q *Queries) UpsertAuthenticate(ctx context.Context, arg UpsertAuthenticateParams) error {
	_, err := q.db.ExecContext(ctx, upsertAuthenticate,
		arg.ID,
		arg.IdentityCert,
		arg.SerialNumber,
		arg.Authenticate,
	)
	return err
}

const upsertEnrollment = `-- name: UpsertEnrollment :exec
INSERT INTO
    enrollments (
        id,
        device_id,
        user_id,
        ` + "`" + `type` + "`" + `,
        topic,
        push_magic,
        token_hex,
        last_seen_at,
        token_update_tally
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, 1) AS new ON DUPLICATE KEY
UPDATE
    device_id = new.device_id,
    user_id = new.user_id,
    ` + "`" + `type` + "`" + ` = new.` + "`" + `type` + "`" + `,
    topic = new.topic,
    push_magic = new.push_magic,
    token_hex = new.token_hex,
    enabled = 1,
    last_seen_at = CURRENT_TIMESTAMP,
    enrollments.token_update_tally = enrollments.token_update_tally + 1
`

type UpsertEnrollmentParams struct {
	ID        string
	DeviceID  string
	UserID    sql.NullString
	Type      string
	Topic     string
	PushMagic string
	TokenHex  string
}

func (q *Queries) UpsertEnrollment(ctx context.Context, arg UpsertEnrollmentParams) error {
	_, err := q.db.ExecContext(ctx, upsertEnrollment,
		arg.ID,
		arg.DeviceID,
		arg.UserID,
		arg.Type,
		arg.Topic,
		arg.PushMagic,
		arg.TokenHex,
	)
	return err
}

const upsertUserAuthenticate = `-- name: UpsertUserAuthenticate :exec
INSERT INTO
    users (
        id,
        device_id,
        user_short_name,
        user_long_name,
        user_authenticate,
        user_authenticate_at
    )
VALUES
    (?, ?, ?, ?, ?, CURRENT_TIMESTAMP) AS new ON DUPLICATE KEY
UPDATE
    device_id = new.device_id,
    user_short_name = new.user_short_name,
    user_long_name = new.user_long_name,
    user_authenticate = new.user_authenticate,
    user_authenticate_at = new.user_authenticate_at
`

type UpsertUserAuthenticateParams struct {
	ID               string
	DeviceID         string
	UserShortName    sql.NullString
	UserLongName     sql.NullString
	UserAuthenticate []byte
}

func (q *Queries) UpsertUserAuthenticate(ctx context.Context, arg UpsertUserAuthenticateParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserAuthenticate,
		arg.ID,
		arg.DeviceID,
		arg.UserShortName,
		arg.UserLongName,
		arg.UserAuthenticate,
	)
	return err
}

const upsertUserAuthenticateDigest = `-- name: UpsertUserAuthenticateDigest :exec
INSERT INTO
    users (
        id,
        device_id,
        user_short_name,
        user_long_name,
        user_authenticate_digest,
        user_authenticate_digest_at
    )
VALUES
    (?, ?, ?, ?, ?, CURRENT_TIMESTAMP) AS new ON DUPLICATE KEY
UPDATE
    device_id = new.device_id,
    user_short_name = new.user_short_name,
    user_long_name = new.user_long_name,
    user_authenticate_digest = new.user_authenticate_digest,
    user_authenticate_digest_at = new.user_authenticate_digest_at
`

type UpsertUserAuthenticateDigestParams struct {
	ID                     string
	DeviceID               string
	UserShortName          sql.NullString
	UserLongName           sql.NullString
	UserAuthenticateDigest []byte
}

func (q *Queries) UpsertUserAuthenticateDigest(ctx context.Context, arg UpsertUserAuthenticateDigestParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserAuthenticateDigest,
		arg.ID,
		arg.DeviceID,
		arg.UserShortName,
		arg.UserLongName,
		arg.UserAuthenticateDigest,
	)
	return err
}

const upsertUserTokenUpdate = `-- name: UpsertUserTokenUpdate :exec
INSERT INTO
    users (
        id,
        device_id,
        user_short_name,
        user_long_name,
        token_update,
        token_update_at
    )
VALUES
    (?, ?, ?, ?, ?, CURRENT_TIMESTAMP) AS new ON DUPLICATE KEY
UPDATE
    device_id = new.device_id,
    user_short_name = new.user_short_name,
    user_long_name = new.user_long_name,
    token_update = new.token_update,
    token_update_at = CURRENT_TIMESTAMP
`

type UpsertUserTokenUpdateParams struct {
	ID            string
	DeviceID      string
	UserShortName sql.NullString
	UserLongName  sql.NullString
	TokenUpdate   []byte
}

func (q *Queries) UpsertUserTokenUpdate(ctx context.Context, arg UpsertUserTokenUpdateParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserTokenUpdate,
		arg.ID,
		arg.DeviceID,
		arg.UserShortName,
		arg.UserLongName,
		arg.TokenUpdate,
	)
	return err
}
