// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type CertAuthAssociation struct {
	ID        string
	Sha256    string
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}

type Command struct {
	CommandUuid string
	RequestType string
	Command     []byte
	CreatedAt   sql.NullString
	UpdatedAt   sql.NullString
}

type CommandResult struct {
	ID          string
	CommandUuid string
	Status      string
	Result      []byte
	NotNowAt    sql.NullString
	NotNowTally int32
	CreatedAt   sql.NullString
	UpdatedAt   sql.NullString
}

type Device struct {
	ID                string
	IdentityCert      []byte
	SerialNumber      sql.NullString
	UnlockToken       []byte
	UnlockTokenAt     sql.NullString
	Authenticate      []byte
	AuthenticateAt    string
	TokenUpdate       []byte
	TokenUpdateAt     sql.NullString
	BootstrapTokenB64 []byte
	BootstrapTokenAt  sql.NullString
	CreatedAt         sql.NullString
	UpdatedAt         sql.NullString
}

type Enrollment struct {
	ID               string
	DeviceID         string
	UserID           sql.NullString
	Type             string
	Topic            string
	PushMagic        string
	TokenHex         string
	Enabled          bool
	TokenUpdateTally int32
	LastSeenAt       string
	CreatedAt        sql.NullString
	UpdatedAt        sql.NullString
}

type EnrollmentQueue struct {
	ID          string
	CommandUuid string
	Active      bool
	Priority    int8
	CreatedAt   sql.NullString
	UpdatedAt   sql.NullString
}

type PushCert struct {
	Topic      string
	CertPem    []byte
	KeyPem     []byte
	StaleToken int32
	CreatedAt  sql.NullString
	UpdatedAt  sql.NullString
}

type User struct {
	ID                       string
	DeviceID                 string
	UserShortName            sql.NullString
	UserLongName             sql.NullString
	TokenUpdate              []byte
	TokenUpdateAt            sql.NullString
	UserAuthenticate         []byte
	UserAuthenticateAt       sql.NullString
	UserAuthenticateDigest   []byte
	UserAuthenticateDigestAt sql.NullString
	CreatedAt                sql.NullString
	UpdatedAt                sql.NullString
}

type ViewQueue struct {
	ID              string
	CreatedAt       sql.NullString
	Active          bool
	Priority        int8
	CommandUuid     string
	RequestType     string
	Command         []byte
	ResultUpdatedAt sql.NullString
	Status          sql.NullString
	Result          sql.NullString
}
