// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
	"time"
)

type CertAuthAssociation struct {
	ID        string
	Sha256    string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Command struct {
	CommandUuid string
	RequestType string
	Command     string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type CommandResult struct {
	ID          string
	CommandUuid string
	Status      string
	Result      string
	NotNowAt    sql.NullTime
	NotNowTally int32
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Device struct {
	ID                string
	IdentityCert      sql.NullString
	SerialNumber      sql.NullString
	UnlockToken       sql.NullString
	UnlockTokenAt     sql.NullTime
	Authenticate      string
	AuthenticateAt    time.Time
	TokenUpdate       sql.NullString
	TokenUpdateAt     sql.NullTime
	BootstrapTokenB64 sql.NullString
	BootstrapTokenAt  sql.NullTime
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

type Enrollment struct {
	ID               string
	DeviceID         string
	UserID           sql.NullString
	Type             string
	Topic            string
	PushMagic        string
	TokenHex         string
	Enabled          bool
	TokenUpdateTally int32
	LastSeenAt       time.Time
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type EnrollmentQueue struct {
	ID          string
	CommandUuid string
	Active      bool
	Priority    int8
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type PushCert struct {
	Topic      string
	CertPem    string
	KeyPem     string
	StaleToken int32
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type User struct {
	ID                       string
	DeviceID                 string
	UserShortName            sql.NullString
	UserLongName             sql.NullString
	TokenUpdate              sql.NullString
	TokenUpdateAt            sql.NullTime
	UserAuthenticate         sql.NullString
	UserAuthenticateAt       sql.NullTime
	UserAuthenticateDigest   sql.NullString
	UserAuthenticateDigestAt sql.NullTime
	CreatedAt                sql.NullTime
	UpdatedAt                sql.NullTime
}

type ViewQueue struct {
	ID              string
	CreatedAt       sql.NullTime
	Active          bool
	Priority        int8
	CommandUuid     string
	RequestType     string
	Command         string
	ResultUpdatedAt sql.NullTime
	Status          sql.NullString
	Result          sql.NullString
}
