// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mysql.sql

package sqlc

import (
	"context"
)

const updateEnrollmentLastSeen = `-- name: UpdateEnrollmentLastSeen :exec
UPDATE
    enrollments
SET
    last_seen_at = CURRENT_TIMESTAMP
WHERE
    id = ?
`

func (q *Queries) UpdateEnrollmentLastSeen(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateEnrollmentLastSeen, id)
	return err
}
