// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push.sql

package sqlc

import (
	"context"
	"strings"
)

const selectPushInfo = `-- name: SelectPushInfo :many
SELECT
    id,
    topic,
    push_magic,
    token_hex
FROM
    enrollments
WHERE
    id IN (/*SLICE:ids*/?)
`

type SelectPushInfoRow struct {
	ID        string
	Topic     string
	PushMagic string
	TokenHex  string
}

func (q *Queries) SelectPushInfo(ctx context.Context, ids []string) ([]SelectPushInfoRow, error) {
	query := selectPushInfo
	var queryParams []any
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectPushInfoRow
	for rows.Next() {
		var i SelectPushInfoRow
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.PushMagic,
			&i.TokenHex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
