// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pushcert.sql

package sqlc

import (
	"context"
)

const selectPushCert = `-- name: SelectPushCert :one
SELECT
    cert_pem,
    key_pem,
    stale_token
FROM
    push_certs
WHERE
    topic = ?
`

type SelectPushCertRow struct {
	CertPem    []byte
	KeyPem     []byte
	StaleToken int32
}

func (q *Queries) SelectPushCert(ctx context.Context, topic string) (SelectPushCertRow, error) {
	row := q.db.QueryRowContext(ctx, selectPushCert, topic)
	var i SelectPushCertRow
	err := row.Scan(&i.CertPem, &i.KeyPem, &i.StaleToken)
	return i, err
}

const selectPushCertStaleToken = `-- name: SelectPushCertStaleToken :one
SELECT
    stale_token
FROM
    push_certs
WHERE
    topic = ?
`

func (q *Queries) SelectPushCertStaleToken(ctx context.Context, topic string) (int32, error) {
	row := q.db.QueryRowContext(ctx, selectPushCertStaleToken, topic)
	var stale_token int32
	err := row.Scan(&stale_token)
	return stale_token, err
}

const upsertPushCert = `-- name: UpsertPushCert :exec
INSERT INTO
    push_certs (topic, cert_pem, key_pem, stale_token)
VALUES
    (?, ?, ?, 0) AS new ON DUPLICATE KEY
UPDATE
    cert_pem = new.cert_pem,
    key_pem = new.key_pem,
    push_certs.stale_token = push_certs.stale_token + 1
`

type UpsertPushCertParams struct {
	Topic   string
	CertPem []byte
	KeyPem  []byte
}

func (q *Queries) UpsertPushCert(ctx context.Context, arg UpsertPushCertParams) error {
	_, err := q.db.ExecContext(ctx, upsertPushCert, arg.Topic, arg.CertPem, arg.KeyPem)
	return err
}
