// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const disableEnrollment = `-- name: DisableEnrollment :exec
UPDATE
  enrollments
SET
  enabled = 0,
  token_update_tally = 0,
  last_seen_at = CURRENT_TIMESTAMP
WHERE
  device_id = ? AND
  enabled = 1
`

func (q *Queries) DisableEnrollment(ctx context.Context, deviceID string) error {
	_, err := q.db.ExecContext(ctx, disableEnrollment, deviceID)
	return err
}

const retrieveTokenUpdateTally = `-- name: RetrieveTokenUpdateTally :one
SELECT token_update_tally FROM enrollments WHERE id = ?
`

func (q *Queries) RetrieveTokenUpdateTally(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRowContext(ctx, retrieveTokenUpdateTally, id)
	var token_update_tally int32
	err := row.Scan(&token_update_tally)
	return token_update_tally, err
}

const storeDeviceTokenUpdateWithUnlock = `-- name: StoreDeviceTokenUpdateWithUnlock :exec
UPDATE devices
SET
    token_update = ?,
    token_update_at = CURRENT_TIMESTAMP,
    unlock_token = ?,
    unlock_token_at = CURRENT_TIMESTAMP
WHERE id = ? LIMIT 1
`

type StoreDeviceTokenUpdateWithUnlockParams struct {
	TokenUpdate sql.NullString
	UnlockToken sql.NullString
	ID          string
}

func (q *Queries) StoreDeviceTokenUpdateWithUnlock(ctx context.Context, arg StoreDeviceTokenUpdateWithUnlockParams) error {
	_, err := q.db.ExecContext(ctx, storeDeviceTokenUpdateWithUnlock, arg.TokenUpdate, arg.UnlockToken, arg.ID)
	return err
}

const storeDeviceTokenUpdateWithoutUnlock = `-- name: StoreDeviceTokenUpdateWithoutUnlock :exec
UPDATE devices
SET
    token_update = ?,
    token_update_at = CURRENT_TIMESTAMP
WHERE id = ? LIMIT 1
`

type StoreDeviceTokenUpdateWithoutUnlockParams struct {
	TokenUpdate sql.NullString
	ID          string
}

func (q *Queries) StoreDeviceTokenUpdateWithoutUnlock(ctx context.Context, arg StoreDeviceTokenUpdateWithoutUnlockParams) error {
	_, err := q.db.ExecContext(ctx, storeDeviceTokenUpdateWithoutUnlock, arg.TokenUpdate, arg.ID)
	return err
}

const updateLastSeen = `-- name: UpdateLastSeen :exec
UPDATE enrollments SET last_seen_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) UpdateLastSeen(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateLastSeen, id)
	return err
}
