// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package sqlc

import (
	"context"
)

const disableEnrollment = `-- name: DisableEnrollment :exec
UPDATE
  enrollments
SET
  enabled = 0,
  token_update_tally = 0,
  last_seen_at = CURRENT_TIMESTAMP
WHERE
  device_id = ? AND
  enabled = 1
`

func (q *Queries) DisableEnrollment(ctx context.Context, deviceID string) error {
	_, err := q.db.ExecContext(ctx, disableEnrollment, deviceID)
	return err
}

const retrieveTokenUpdateTally = `-- name: RetrieveTokenUpdateTally :one
SELECT token_update_tally FROM enrollments WHERE id = ?
`

func (q *Queries) RetrieveTokenUpdateTally(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRowContext(ctx, retrieveTokenUpdateTally, id)
	var token_update_tally int32
	err := row.Scan(&token_update_tally)
	return token_update_tally, err
}

const updateLastSeen = `-- name: UpdateLastSeen :exec
UPDATE enrollments SET last_seen_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) UpdateLastSeen(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateLastSeen, id)
	return err
}
