// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queue.sql

package sqlc

import (
	"context"
)

const deleteCommandResultForID = `-- name: DeleteCommandResultForID :exec
DELETE q,
r
FROM
    enrollment_queue AS q
    LEFT JOIN command_results AS r ON q.command_uuid = r.command_uuid
    AND r.id = q.id
WHERE
    q.id = ?
    AND q.command_uuid = ?
`

type DeleteCommandResultForIDParams struct {
	ID          string
	CommandUuid string
}

func (q *Queries) DeleteCommandResultForID(ctx context.Context, arg DeleteCommandResultForIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteCommandResultForID, arg.ID, arg.CommandUuid)
	return err
}

const deleteCommandWhereComplete = `-- name: DeleteCommandWhereComplete :exec
DELETE c
FROM
    commands AS c
    LEFT JOIN enrollment_queue AS q ON q.command_uuid = c.command_uuid
    LEFT JOIN command_results AS r ON r.command_uuid = c.command_uuid
WHERE
    c.command_uuid = ?
    AND q.command_uuid IS NULL
    AND r.command_uuid IS NULL
`

func (q *Queries) DeleteCommandWhereComplete(ctx context.Context, commandUuid string) error {
	_, err := q.db.ExecContext(ctx, deleteCommandWhereComplete, commandUuid)
	return err
}

const insertCommands = `-- name: InsertCommands :exec
INSERT INTO
    commands (command_uuid, request_type, command)
VALUES
    (?, ?, ?)
`

type InsertCommandsParams struct {
	CommandUuid string
	RequestType string
	Command     []byte
}

func (q *Queries) InsertCommands(ctx context.Context, arg InsertCommandsParams) error {
	_, err := q.db.ExecContext(ctx, insertCommands, arg.CommandUuid, arg.RequestType, arg.Command)
	return err
}

const lockCommandsForDelete = `-- name: LockCommandsForDelete :exec
SELECT
    command_uuid
FROM
    commands
WHERE
    command_uuid = ? FOR
UPDATE
`

func (q *Queries) LockCommandsForDelete(ctx context.Context, commandUuid string) error {
	_, err := q.db.ExecContext(ctx, lockCommandsForDelete, commandUuid)
	return err
}

const selectNextCommand = `-- name: SelectNextCommand :one
SELECT
    c.command_uuid,
    c.request_type,
    c.command
FROM
    enrollment_queue AS q
    INNER JOIN commands AS c ON q.command_uuid = c.command_uuid
    LEFT JOIN command_results r ON r.command_uuid = q.command_uuid
    AND r.id = q.id
WHERE
    q.id = ?
    AND q.active = 1
    AND (
        r.status IS NULL
        OR (
            r.status = 'NotNow'
            AND CAST(? AS SIGNED)
        )
    )
ORDER BY
    q.priority DESC,
    q.created_at
LIMIT
    1
`

type SelectNextCommandParams struct {
	ID            string
	IncludeNotNow int64
}

type SelectNextCommandRow struct {
	CommandUuid string
	RequestType string
	Command     []byte
}

func (q *Queries) SelectNextCommand(ctx context.Context, arg SelectNextCommandParams) (SelectNextCommandRow, error) {
	row := q.db.QueryRowContext(ctx, selectNextCommand, arg.ID, arg.IncludeNotNow)
	var i SelectNextCommandRow
	err := row.Scan(&i.CommandUuid, &i.RequestType, &i.Command)
	return i, err
}

const updateClearQueue = `-- name: UpdateClearQueue :exec
UPDATE
    enrollment_queue AS q
    INNER JOIN enrollments AS e ON q.id = e.id
    INNER JOIN commands AS c ON q.command_uuid = c.command_uuid
    LEFT JOIN command_results r ON r.command_uuid = q.command_uuid
    AND r.id = q.id
SET
    q.active = 0
WHERE
    e.device_id = ?
    AND active = 1
    AND (
        r.status IS NULL
        OR r.status = 'NotNow'
    )
`

func (q *Queries) UpdateClearQueue(ctx context.Context, deviceID string) error {
	_, err := q.db.ExecContext(ctx, updateClearQueue, deviceID)
	return err
}

const upsertCommandReport = `-- name: UpsertCommandReport :exec
INSERT INTO
    command_results (
        id,
        command_uuid,
        ` + "`" + `status` + "`" + `,
        result
    )
VALUES
    (?, ?, ?, ?) AS new ON DUPLICATE KEY
UPDATE
    ` + "`" + `status` + "`" + ` = new.` + "`" + `status` + "`" + `,
    result = new.result
`

type UpsertCommandReportParams struct {
	ID          string
	CommandUuid string
	Status      string
	Result      []byte
}

func (q *Queries) UpsertCommandReport(ctx context.Context, arg UpsertCommandReportParams) error {
	_, err := q.db.ExecContext(ctx, upsertCommandReport,
		arg.ID,
		arg.CommandUuid,
		arg.Status,
		arg.Result,
	)
	return err
}

const upsertCommandReportNotNow = `-- name: UpsertCommandReportNotNow :exec
INSERT INTO
    command_results (
        id,
        command_uuid,
        ` + "`" + `status` + "`" + `,
        result,
        not_now_at,
        not_now_tally
    )
VALUES
    (?, ?, ?, ?, CURRENT_TIMESTAMP, 1) AS new ON DUPLICATE KEY
UPDATE
    ` + "`" + `status` + "`" + ` = new.` + "`" + `status` + "`" + `,
    result = new.result,
    command_results.not_now_tally = command_results.not_now_tally + 1
`

type UpsertCommandReportNotNowParams struct {
	ID          string
	CommandUuid string
	Status      string
	Result      []byte
}

func (q *Queries) UpsertCommandReportNotNow(ctx context.Context, arg UpsertCommandReportNotNowParams) error {
	_, err := q.db.ExecContext(ctx, upsertCommandReportNotNow,
		arg.ID,
		arg.CommandUuid,
		arg.Status,
		arg.Result,
	)
	return err
}
